# This is a basic workflow to help you get started with Actions

name: stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubantu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
